baseURL = "https://amaliedue.github.io/multisig-hmac-website/"
languageCode = "en-us"
title = "Multisig HMAC"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = ""
  facebook = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/AmalieDue/"
  gitlab = ""
  twitter = "https://twitter.com/DueAmalie"
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2

## Main Menu
[[menu.main]]
    name = "Java"
    weight = 100
    identifier = "Java"
    url = "/#java"
[[menu.main]]
    name = "Javascript"
    identifier = "Javascript"
    weight = 200
    url = "/#javascript"
[[menu.main]]
    name = "Python"
    identifier = "Python"
    weight = 300
    url = "/#python"
